# ref: https://docs.travis-ci.com/user/languages/python
language: python
sudo: true
env:
  - TOXENV=py35
  - TOXENV=py34
  - TOXENV=py27
  - TOXENV=py27-functional
  - TOXENV=py35-functional
  - TOXENV=update-pep8
  - TOXENV=docs
  - TOXENV=coverage,codecov

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" upgrade
  - sudo apt-get -y install software-properties-common
  - sudo cat /usr/lib/python2.7/dist-packages/softwareproperties/cloudarchive.py
  - sudo add-apt-repository -y cloud-archive:icehouse
  - sudo apt-get -qq update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install libvirt-dev libvirt-bin qemu-kvm qemu virtinst bridge-utils
  - sudo usermod -a -G libvirtd travis
  - sudo chmod a+rwx /var/run/libvirt/libvirt-sock*

install:
  - pip install tox

script:
  - tox
